name: Run Jest Sanity Tests

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies

      run: npm install

    - name: create env file
      run: |
        touch .env
        echo ONE_API_KEY=${{ secrets.ONE_API_KEY }} >> .env

    - name: Run Jest test
      run: npm test
